# Application Configuration
spring.application.name=library-management-system
server.port=8080

# Database Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/library_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=root
# For AWS RDS MySQL
spring.datasource.url=jdbc:mysql://library-db.cnscm6eme5ho.ap-south-1.rds.amazonaws.com:3306/library_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=password

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=VGhpc0lzQVNlY3JldEtleUZvckpXVFRva2VuVGhpc0lzQVNlY3JldEtleQ==
jwt.expiration= 21600000

# CORS Configuration
cors.allowed-origins=http://localhost:5173,https://yourdomain.com

# Enable devtools restart
spring.devtools.restart.enabled=true

# Enable LiveReload (only affects browser, not Postman)
spring.devtools.livereload.enabled=true

# Optional: additional folders to watch
spring.devtools.restart.additional-paths=src/main/java,src/main/resources

# Logging
logging.level.com.library=DEBUG
logging.level.org.springframework.security=DEBUG

# Avoid null
spring.jackson.default-property-inclusion=non_null